### ISSUE TITLE
报错怎么解决

### ISSUE THREAD

**Issue by kevinls0823** [wux1an/wxapkg#28]
D:\ChromeDownloader>wxapkg_1.5.0_windows_amd64.exe scan
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        github.com/charmbracelet/bubbletea@v0.24.1/tea.go:440 +0x95
panic({0xee9bc0, 0xc0000208e8})
        runtime/panic.go:890 +0x262
github.com/wux1an/wxapkg/cmd.(*scanTui).renderDetail(0x12fd8a0?)
        github.com/wux1an/wxapkg/cmd/scan-tui.go:123 +0x805
github.com/wux1an/wxapkg/cmd.(*scanTui).View(0xc000198000)
        github.com/wux1an/wxapkg/cmd/scan-tui.go:176 +0x12e
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00019a000)
        github.com/charmbracelet/bubbletea@v0.24.1/tea.go:487 +0x6f5
github.com/wux1an/wxapkg/cmd.glob..func1(0x12f7640?, {0xf0f652?, 0x0?, 0x0?})
        github.com/wux1an/wxapkg/cmd/scan.go:51 +0x1cc

**Comment by Hundredsu** [comment]
解决了吗？同问

**Comment by cokyrain** [comment]
wxapkg_1.5.0_windows_amd64 scan -r "Applet文件夹的绝对路径"
