### ISSUE TITLE
我发现一个问题，就是电脑上的微信没打开过小程序，执行scan命令的时候会报数组越界

### ISSUE THREAD

**Issue by fengzi1207** [wux1an/wxapkg#37]
![微信图片_20241207210248](https://github.com/user-attachments/assets/f6d4dd60-dc36-4d90-9405-b8b60e115a79)

**Comment by kaka77** [comment]
+1  同样问题

```
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        github.com/charmbracelet/bubbletea@v0.24.1/tea.go:440 +0x95
panic({0xdd9bc0, 0xc00009c108})
        runtime/panic.go:890 +0x262
github.com/wux1an/wxapkg/cmd.(*scanTui).renderDetail(0x11ed8a0?)
        github.com/wux1an/wxapkg/cmd/scan-tui.go:123 +0x805
github.com/wux1an/wxapkg/cmd.(*scanTui).View(0xc0000c4600)
        github.com/wux1an/wxapkg/cmd/scan-tui.go:176 +0x12e
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000c8000)
        github.com/charmbracelet/bubbletea@v0.24.1/tea.go:487 +0x6f5
github.com/wux1an/wxapkg/cmd.glob..func1(0x11e7640?, {0xdff652?, 0x0?, 0x0?})
        github.com/wux1an/wxapkg/cmd/scan.go:51 +0x1cc
github.com/spf13/cobra.(*Command).execute(0x11e7640, {0x1244ae8, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x11e7080)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/wux1an/wxapkg/cmd.Execute()
        github.com/wux1an/wxapkg/cmd/root.go:18 +0x25
main.main()
        github.com/wux1an/wxapkg/main.go:13 +0xbc

```

**Comment by ChuangSR** [comment]
打开一个小程序就好了，而且不知道为什么第一个小程序会出错，后面的就是正常的

**Comment by yangwang-1211** [comment]
大佬们解决了么？我这还是有这个问题

**Comment by b2522** [comment]
看一下你的小程序目录在哪里，使用 -r参数指定一下，就可以运行了。
我用下面的命令，weixinname换成你自己的。
wxapkg_1.5.0_windows_amd64.exe scan -r "C:\Users\Administrator\Documents\WeChat Files\weixinname\Applet"
